In [4]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [5]:
iris = load_iris()

X = iris.data
y = iris.target


print("Input Data Shape:", X.shape)
print("Target Shape:", y.shape)

Input Data Shape: (150, 4)
Target Shape: (150,)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


print("Training Data:",X_train.shape)
print("Testing Data:",X_test.shape)

Training Data: (120, 4)
Testing Data: (30, 4)


In [7]:
scaler = StandardScaler()


X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [8]:
k = 5


model = KNeighborsClassifier(
    n_neighbors=k
)


model.fit(
    X_train,
    y_train
)


print("Model Training Completed")

Model Training Completed


In [9]:
y_pred = model.predict(X_test)


print("Predicted Values:")
print(y_pred)


print("\nActual Values:")
print(y_test)

Predicted Values:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]

Actual Values:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [10]:
accuracy = accuracy_score(
    y_test,
    y_pred
)


print("Accuracy =",accuracy*100,"%")

Accuracy = 100.0 %


In [11]:
cm = confusion_matrix(
    y_test,
    y_pred
)


print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [12]:
new_sample = [[5.1,3.5,1.4,0.2]]


new_sample = scaler.transform(new_sample)


prediction = model.predict(new_sample)


print(
    "Predicted Class:",
    iris.target_names[prediction][0]
)


Predicted Class: setosa
